#!/bin/sh

################################################################################
#      This file is part of CoreELEC - http://coreelec.org
#      Copyright (C) 2018-present Team CoreELEC
#
#  CoreELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  CoreELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with CoreELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

for i in /storage/.config/rc_keymaps/*; do
  sed -i 's/KEY_INFO/KEY_I/g' $i
  sed -i 's/KEY_CONTEXT_MENU/KEY_O/g' $i
  sed -i 's/KEY_CHANNELUP/KEY_PAGEUP/g' $i
  sed -i 's/KEY_CHANNELDOWN/KEY_PAGEDOWN/g' $i
  sed -i 's/KEY_OK/KEY_ENTER/g' $i
  sed -i 's/KEY_LANGUAGE/KEY_GRAVE/g' $i
  sed -i 's/KEY_SUBTITLE/KEY_L/g' $i
done
